[package]
name = "bindmount"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
libc.version = "0.2.169"
libc.default-features = false
linux-syscalls.default-features = false
linux-syscalls.version = "0.4.0"
